#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Aliases
alias sudo='sudo env PATH=$PATH'
alias tmux='tmux -2'
alias diff='colordiff'

alias ll='ls++'

alias v='fasd -f -e vim' # quick opening files with vim

alias proxy='env {http,https,ftp}_proxy=http://localhost:5865'
alias export-proxy='export {http,https,ftp}_proxy=http://localhost:5865'

alias git-proxy='GIT_PROXY_COMMAND=$HOME/workarea/embedded/android/bin/socks-gw.sh'
